[package]
name = "blockchain_core"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
p256 = "0.13.2"
rand = "0.9.0"
rand_core = { version = "0.9.3", feature = "getrandom" }
sha2 = "0.10.8"
